name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy to EC2 via SSH
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd ~/murphdunks
            git pull origin main

            # Copy frontend files to Nginx web root
            sudo cp index.html /var/www/html/
            sudo cp style.css /var/www/html/
            sudo cp script.js /var/www/html/
            sudo cp about.html /var/www/html/
            sudo cp faq.html /var/www/html/
            sudo cp progress.html /var/www/html/
            sudo cp cancel.html /var/www/html/
            sudo cp success.html /var/www/html/

            cd backend
            npm install
            pm2 restart murphdunks
